### ISSUE TITLE
feat: Implement table functions

### ISSUE THREAD

**Issue by purplefox** [confluentinc/ksql#3504]
This is a super task for all the tasks involved in the implementation of this feature.

The table function prototype is here https://github.com/purplefox/ksql/pull/6
Related issue with discussion is here: https://github.com/confluentinc/ksql/issues/527

Sub tasks:

- [x] - [feat: Create KLIP for table functions feature](https://github.com/confluentinc/ksql/issues/3512)
- [x] - [feat: Disallow aggregates together with table functions](https://github.com/confluentinc/ksql/issues/3661)
- [x] - [feat: Implement EXPLODE(ARRAY<V>)](https://github.com/confluentinc/ksql/issues/3505)
- [x] - [feat: Extend table function implementation to support multiple functions in SELECT](https://github.com/confluentinc/ksql/issues/3513)
- [x] - [feat: Evaluate table functions against more complex expressions](https://github.com/confluentinc/ksql/issues/3514)
- [x] - [feat: Implement ENTRIES(MAP)](https://github.com/confluentinc/ksql/issues/3506)
- [x] - [feat: Implement SERIES UDF](https://github.com/confluentinc/ksql/issues/3507)
- [x] - [feat: Implement UDTFs](https://github.com/confluentinc/ksql/issues/3508)
- [x] - [feat: Implement schemaProvider for UDTFs](https://github.com/confluentinc/ksql/issues/3688)
- [x] - [feat: Augment list functions and describe function to include table functions](https://github.com/confluentinc/ksql/issues/3517)
- [x] - [docs: Update syntax reference for built-in table functions ](https://github.com/confluentinc/ksql/issues/3509)
- [x] - [docs: Update developer guide for table functions](https://github.com/confluentinc/ksql/issues/3510)
- [x] - [docs: Add new example for table functions](https://github.com/confluentinc/ksql/issues/3511)
