### ISSUE TITLE
Primitive Key Epic

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#3533]
This issue tracks remaining work for extending KSQL's support of key types beyond just `STRING` to other primitive key types.

#### Subtasks:
- [ ] [Support `INT`, `BIGINT`, `DOUBLE` and `STRING`](https://github.com/confluentinc/ksql/issues/3534)
- [ ] [Support `DECIMAL` keys](https://github.com/confluentinc/ksql/issues/3535)
- [ ] [allow key names other than ROWKEY](https://github.com/confluentinc/ksql/issues/3536)
- [ ] [Deprecate `WITH(KEY='z')`](https://github.com/confluentinc/ksql/issues/3537)

#### Optional:
- [ ] Consider supporting `PRIMARY KEY` syntax on tables vs `KEY` syntax on streams.
- [ ] [`LogicalSchema` should also include `WindowType`](https://github.com/confluentinc/ksql/issues/3574)

**Comment by big-andy-coates** [comment]
Replaced by: https://github.com/confluentinc/ksql/projects/3
