### ISSUE TITLE
Pull Query Epic

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#3548]
This issue tracks remaining work for the initial phase of pull queries

#### Subtasks:
- [ ] [Use logical and physical query planners](https://github.com/confluentinc/ksql/issues/3541)
- [ ] [Perf test](https://github.com/confluentinc/ksql/issues/3545)
- [ ] [Support arbitrary pull queries](https://github.com/confluentinc/ksql/issues/3546)
- [ ] [Make timeouts configurable](https://github.com/confluentinc/ksql/issues/3573)
- [ ] [Pass client side property overrides through proxy](https://github.com/confluentinc/ksql/issues/3577)
- [ ] [pass any previous command id through proxy](https://github.com/confluentinc/ksql/issues/3578)
- [ ] [continuous queries should start from beginning](https://github.com/confluentinc/ksql/issues/3579)
- [ ] [document how to use standby nodes to improve availability](https://github.com/confluentinc/ksql/issues/3580)
- [ ] [Restructure code](https://github.com/confluentinc/ksql/issues/3581)
- [ ] [Add metrics](https://github.com/confluentinc/ksql/issues/3582)
- [ ] [Better formatting of output](https://github.com/confluentinc/ksql/issues/3643)

#### Possible perf improvements:
- [ ] [pre-compile known steps](https://github.com/confluentinc/ksql/issues/3542)
- [ ] [templated pre-compiled expected WHERE clauses](https://github.com/confluentinc/ksql/issues/3544)

#### Requested enhancements:
- [ ] [KEY field support](https://github.com/confluentinc/ksql/issues/3527)
- [ ] [pseudo support for structured keys](https://github.com/confluentinc/ksql/issues/3584)
- [ ] [Better error message](https://github.com/confluentinc/ksql/issues/3524)
- [ ] [Improve REST response format](https://github.com/confluentinc/ksql/issues/3526)
- [ ] [Error says table when its a stream](https://github.com/confluentinc/ksql/issues/3523)
- [ ] [Syntax change error message improvements](https://github.com/confluentinc/ksql/issues/3521)
- [ ] [Support WINDOWSTART in projection of pull queries](https://github.com/confluentinc/ksql/issues/3633)

#### Known Bugs:
- [ ] [ROWKEY used in expression fails](https://github.com/confluentinc/ksql/issues/3498)
- [ ] [EXPLAIN returns KS topology](https://github.com/confluentinc/ksql/issues/3495)

#### Future:
- [ ] [Cache arbitrary pull queries](https://github.com/confluentinc/ksql/issues/3547)
- [ ] [stream back chunked response for large data set](https://github.com/confluentinc/ksql/issues/3575)
- [ ] [include unique correlation id in processing logs](https://github.com/confluentinc/ksql/issues/3576)
- [ ] [standardize WINDOWSTART WHERE clause handling](https://github.com/confluentinc/ksql/issues/3583)
- [ ] [Suppport ROWTIME in pull queries](https://github.com/confluentinc/ksql/issues/3623)

**Comment by apurvam** [comment]
cc @vinothchandar

**Comment by apurvam** [comment]
We may want to consider adding pagination support to lookup queries on tables. https://github.com/confluentinc/ksql/issues/528

**Comment by big-andy-coates** [comment]
Now tracking through https://github.com/confluentinc/ksql/projects/2
