### ISSUE TITLE
UDF Epic

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#3556]
This issue tracks upcoming work around the UDF/UDAF framework.  The initial work for UDTFs can be found in https://github.com/confluentinc/ksql/issues/3504.

#### Subtask
- [ ] [Consistent types across UDFs and UDAFs](https://github.com/confluentinc/ksql/issues/3553)
- [ ] [remove dependencies on Connect Schema type](https://github.com/confluentinc/ksql/issues/3554)
- [ ] [complete decimal support](https://github.com/confluentinc/ksql/issues/3555)

**Comment by big-andy-coates** [comment]
Replaced by: https://github.com/confluentinc/ksql/projects/4?add_cards_query=is%3Aopen
