### ISSUE TITLE
New Server API Phase 1

### ISSUE THREAD

**Issue by purplefox** [confluentinc/ksql#4254]
Please see https://github.com/confluentinc/ksql/pull/4069 

This is an umbrella issue to track the development of the new HTTP2 Server API.

Phase 1 includes the minimum functionality required to implement a demo ride sharing app.

Once it has been completed, we can start phase 2 https://github.com/confluentinc/ksql/issues/4266

Phase 1 is mainly:

* Implement server->client query streaming API for pull and push queries
* Implement client->server inserts streaming API

- [x] -  [Implement bare bones API server](https://github.com/confluentinc/ksql/issues/4255)
- [x] - [Push query server implementation](https://github.com/confluentinc/ksql/issues/4256)
- [x] - [Pull query server implementation](https://github.com/confluentinc/ksql/issues/4257)
- [x] - [Inserts server implementation](https://github.com/confluentinc/ksql/issues/4263)
- [x] - [Implement basic auth for the new API](https://github.com/confluentinc/ksql/issues/4264)
- [x] - [Provide benchmarks for new API](https://github.com/confluentinc/ksql/issues/4279)
- [x] - [Integrate reactive streams TCK into test suite](https://github.com/confluentinc/ksql/issues/4289)
- [x] - [Allow for writing response as single JSON object](https://github.com/confluentinc/ksql/issues/4317)
- [x] - [Consider using AbstractConfig for server config](https://github.com/confluentinc/ksql/issues/4330)
- [x] - [Consider using Hamcrest for test assertions](https://github.com/confluentinc/ksql/issues/4332)
- [x] - [Consider using POJOs to represent endpoint arguments](https://github.com/confluentinc/ksql/issues/4333)
- [x] - [Use JKS SSL config for the new API](https://github.com/confluentinc/ksql/issues/4528)
- [x] - [Provide upper limit for number of push queries](https://github.com/confluentinc/ksql/issues/4578)

**Comment by vcrfxia** [comment]
Marking this as done 🎉
